import type { ProviderDef } from "../config/types.js";

/**
 * Built-in provider catalog.
 *
 * Only the transport details live here — base URL, credential style, wire
 * format. Model lists are discovered at runtime from each provider's
 * `GET /models` endpoint (see src/routing/modelIndex.ts), so this file does
 * not go stale every time a provider ships a new model. The `models` hints
 * below exist only to seed routing before the first discovery completes.
 *
 * Anything not listed here can be added through the JSON config file; see
 * config/gateway.example.json.
 */

const PRIORITY_LOCAL = 50;
const PRIORITY_FREE = 100;
const PRIORITY_PAID = 200;

export const BUILTIN_PROVIDERS: ProviderDef[] = [
  // --- Local runtimes (no credential) --------------------------------------
  {
    id: "ollama",
    label: "Ollama",
    baseUrl: "http://localhost:11434/v1",
    baseUrlEnv: "OLLAMA_BASE_URL",
    enableEnv: "OLLAMA_ENABLED",
    wire: "openai",
    auth: "none",
    local: true,
    free: true,
    priority: PRIORITY_LOCAL,
  },
  {
    id: "lmstudio",
    label: "LM Studio",
    baseUrl: "http://localhost:1234/v1",
    baseUrlEnv: "LMSTUDIO_BASE_URL",
    enableEnv: "LMSTUDIO_ENABLED",
    wire: "openai",
    auth: "none",
    local: true,
    free: true,
    priority: PRIORITY_LOCAL,
  },
  {
    id: "llamacpp",
    label: "llama.cpp server",
    baseUrl: "http://localhost:8080/v1",
    baseUrlEnv: "LLAMACPP_BASE_URL",
    enableEnv: "LLAMACPP_ENABLED",
    wire: "openai",
    auth: "none",
    local: true,
    free: true,
    priority: PRIORITY_LOCAL,
  },
  {
    id: "vllm",
    label: "vLLM",
    baseUrl: "http://localhost:8000/v1",
    baseUrlEnv: "VLLM_BASE_URL",
    enableEnv: "VLLM_ENABLED",
    wire: "openai",
    auth: "none",
    local: true,
    free: true,
    priority: PRIORITY_LOCAL,
  },

  // --- Free / freemium hosted tiers ----------------------------------------
  {
    id: "groq",
    label: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    baseUrlEnv: "GROQ_BASE_URL",
    apiKeyEnv: "GROQ_API_KEY",
    wire: "openai",
    auth: "bearer",
    free: true,
    priority: PRIORITY_FREE,
  },
  {
    id: "cerebras",
    label: "Cerebras",
    baseUrl: "https://api.cerebras.ai/v1",
    baseUrlEnv: "CEREBRAS_BASE_URL",
    apiKeyEnv: "CEREBRAS_API_KEY",
    wire: "openai",
    auth: "bearer",
    free: true,
    priority: PRIORITY_FREE,
  },
  {
    id: "google",
    label: "Google AI Studio (Gemini)",
    // Gemini exposes an OpenAI-compatible surface at this path.
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    baseUrlEnv: "GOOGLE_BASE_URL",
    apiKeyEnv: "GOOGLE_API_KEY",
    wire: "openai",
    auth: "bearer",
    free: true,
    priority: PRIORITY_FREE,
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    baseUrlEnv: "OPENROUTER_BASE_URL",
    apiKeyEnv: "OPENROUTER_API_KEY",
    wire: "openai",
    auth: "bearer",
    free: true,
    priority: PRIORITY_FREE,
    headers: {
      "HTTP-Referer": "https://github.com/Bahaaowaies18-create/Bahaa-Owais",
      "X-Title": "omniroute-gateway",
    },
  },
  {
    id: "github",
    label: "GitHub Models",
    baseUrl: "https://models.github.ai/inference",
    baseUrlEnv: "GITHUB_MODELS_BASE_URL",
    apiKeyEnv: "GITHUB_MODELS_TOKEN",
    wire: "openai",
    auth: "bearer",
    free: true,
    priority: PRIORITY_FREE,
  },
  {
    id: "mistral",
    label: "Mistral",
    baseUrl: "https://api.mistral.ai/v1",
    baseUrlEnv: "MISTRAL_BASE_URL",
    apiKeyEnv: "MISTRAL_API_KEY",
    wire: "openai",
    auth: "bearer",
    free: true,
    priority: PRIORITY_FREE,
  },
  {
    id: "nvidia",
    label: "NVIDIA NIM",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    baseUrlEnv: "NVIDIA_BASE_URL",
    apiKeyEnv: "NVIDIA_API_KEY",
    wire: "openai",
    auth: "bearer",
    free: true,
    priority: PRIORITY_FREE,
  },
  {
    id: "scaleway",
    label: "Scaleway Generative APIs",
    baseUrl: "https://api.scaleway.ai/v1",
    baseUrlEnv: "SCALEWAY_BASE_URL",
    apiKeyEnv: "SCALEWAY_API_KEY",
    wire: "openai",
    auth: "bearer",
    free: true,
    priority: PRIORITY_FREE,
  },

  // --- Paid hosted providers ------------------------------------------------
  {
    id: "openai",
    label: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    baseUrlEnv: "OPENAI_BASE_URL",
    apiKeyEnv: "OPENAI_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "anthropic",
    label: "Anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    baseUrlEnv: "ANTHROPIC_BASE_URL",
    apiKeyEnv: "ANTHROPIC_API_KEY",
    wire: "anthropic",
    auth: "anthropic",
    priority: PRIORITY_PAID,
    headers: { "anthropic-version": "2023-06-01" },
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    baseUrlEnv: "DEEPSEEK_BASE_URL",
    apiKeyEnv: "DEEPSEEK_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "together",
    label: "Together AI",
    baseUrl: "https://api.together.xyz/v1",
    baseUrlEnv: "TOGETHER_BASE_URL",
    apiKeyEnv: "TOGETHER_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "fireworks",
    label: "Fireworks AI",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    baseUrlEnv: "FIREWORKS_BASE_URL",
    apiKeyEnv: "FIREWORKS_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "deepinfra",
    label: "DeepInfra",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    baseUrlEnv: "DEEPINFRA_BASE_URL",
    apiKeyEnv: "DEEPINFRA_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "xai",
    label: "xAI (Grok)",
    baseUrl: "https://api.x.ai/v1",
    baseUrlEnv: "XAI_BASE_URL",
    apiKeyEnv: "XAI_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "perplexity",
    label: "Perplexity",
    baseUrl: "https://api.perplexity.ai",
    baseUrlEnv: "PERPLEXITY_BASE_URL",
    apiKeyEnv: "PERPLEXITY_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
    // Perplexity does not expose a model listing endpoint.
    noModelDiscovery: true,
    models: ["sonar", "sonar-pro", "sonar-reasoning", "sonar-reasoning-pro"],
  },
  {
    id: "hyperbolic",
    label: "Hyperbolic",
    baseUrl: "https://api.hyperbolic.xyz/v1",
    baseUrlEnv: "HYPERBOLIC_BASE_URL",
    apiKeyEnv: "HYPERBOLIC_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "nebius",
    label: "Nebius AI Studio",
    baseUrl: "https://api.studio.nebius.ai/v1",
    baseUrlEnv: "NEBIUS_BASE_URL",
    apiKeyEnv: "NEBIUS_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "sambanova",
    label: "SambaNova",
    baseUrl: "https://api.sambanova.ai/v1",
    baseUrlEnv: "SAMBANOVA_BASE_URL",
    apiKeyEnv: "SAMBANOVA_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "novita",
    label: "Novita AI",
    baseUrl: "https://api.novita.ai/v3/openai",
    baseUrlEnv: "NOVITA_BASE_URL",
    apiKeyEnv: "NOVITA_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "moonshot",
    label: "Moonshot (Kimi)",
    baseUrl: "https://api.moonshot.ai/v1",
    baseUrlEnv: "MOONSHOT_BASE_URL",
    apiKeyEnv: "MOONSHOT_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "zhipu",
    label: "Zhipu AI (GLM)",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    baseUrlEnv: "ZHIPU_BASE_URL",
    apiKeyEnv: "ZHIPU_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "qwen",
    label: "Alibaba DashScope (Qwen)",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    baseUrlEnv: "DASHSCOPE_BASE_URL",
    apiKeyEnv: "DASHSCOPE_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
  {
    id: "ai21",
    label: "AI21 Labs",
    baseUrl: "https://api.ai21.com/studio/v1",
    baseUrlEnv: "AI21_BASE_URL",
    apiKeyEnv: "AI21_API_KEY",
    wire: "openai",
    auth: "bearer",
    priority: PRIORITY_PAID,
  },
];

export const BUILTIN_PROVIDER_IDS = new Set(BUILTIN_PROVIDERS.map((p) => p.id));
